### ISSUE TITLE
Failed to activate the latex-completions package

### ISSUE THREAD

**Issue by nicksilver** [JunoLab/atom-latex-completions#20]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [latex-completions](https://github.com/JunoLab/atom-latex-completions) package, v0.3.2
### Stack Trace

Failed to activate the latex-completions package

```
At Autocomplete provider 'Object(undefined)'
specifies `selector` instead of the `scopeSelector` attribute.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API.

Error: Autocomplete provider 'Object(undefined)'
specifies `selector` instead of the `scopeSelector` attribute.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API.
    at ProviderManager.module.exports.ProviderManager.registerProvider (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/provider-manager.js:302:17)
    at ProviderManager.registerProvider (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/provider-manager.js:3:61)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:83:65
    at Object.module.exports.requireAutocompleteManagerAsync (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:23:49)
    at Object.module.exports.consumeProvider (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:79:12)
    at Object.module.exports.consumeProvider_3_0 (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/main.js:65:19)
    at Provider.module.exports.Provider.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/opt/atom/resources/app.asar/src/package.js:355:71)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:186:16)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:538:21)
    at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:397:31
```
### Commands

```
     -0:15.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-one-dark-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atomic-emacs",
      "emacs-plus"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-material-ui, v1.3.6 (active)
atomic-emacs, v0.9.2 (inactive)
autocomplete-python, v1.8.6 (active)
emacs-plus, v0.11.0 (inactive)
git-plus, v5.17.1 (inactive)
Hydrogen, v0.14.0 (inactive)
ink, v0.5.0 (inactive)
julia-client, v0.5.1 (inactive)
language-julia, v0.6.0 (active)
language-r, v0.4.1 (active)
latex-completions, v0.3.2 (inactive)
platformio-ide-terminal, v2.2.0 (active)
python-indent, v1.0.0 (active)
python-tools, v0.6.8 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
This should only happen upon upgrading the package -- restart Atom and you're good to go.

**Comment by Nectarineimp** [comment]
Confirmed: restarting Atom fixes the issue and we are good to go.
